// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Use pooler for application runtime
    url: env("DATABASE_URL"),
    // Use direct connection for migrations and seeding
    shadowDatabaseUrl: env("DIRECT_URL"),
  },
});
